name: Web Design NJ
favicon: null
layout_spectrum: 0.1347212945111096
typography_spectrum: 0.8322932024020702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4845952419564128
  lightness: 0.11997056496329606
  saturation: 0.24824686371721327
  rhythmicContrast: 0.21871889336034656
purpose: []
