name: Web Design NJ
favicon: null
layout_spectrum: 0.50263
typography_spectrum: 0.62481
title: The DIY Web Guy - Web Design NJ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71132258-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00c2ff'
    - '#333333'
    - '#ff6908'
    - '#ffffff'
    - '#9b9b9b'
  brandStrength: 0.5
  lightness: 0.11997056496329606
  saturation: 0.25
  rhythmicContrast: 0.21871889336034656
purpose: []
